Triggering.

diff --git a/.github/workflows/run-recipe-test.yaml b/.github/workflows/run-recipe-test.yaml
--- a/.github/workflows/run-recipe-test.yaml
+++ b/.github/workflows/run-recipe-test.yaml
@@ -12,10 +12,13 @@ jobs:
           token: ${{ secrets.ACTIONS_BOT_TOKEN }}
           repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
           ref: ${{ github.event.client_payload.pull_request.head.ref }}
-      - name: Dump the client payload context
-        env:
-          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
-        run: echo "$PAYLOAD_CONTEXT"
+        uses: actions/checkout@v2
+
+      - name: Get changed files
+        id: changed-files
+        # Set outputs using the command.
+        run: |
+          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
 
       # - name: Get the files changed in the Pull Request
         # id: changed-files
@@ -27,14 +30,14 @@ jobs:
         # run: |
           # curl https://raw.githubusercontent.com/pangeo-forge/bakery-database/main/bakeries.yaml -o ${GITHUB_WORKSPACE}/bakeries.yaml
 
-      # - name: Locate Pull Requests meta.yaml
-        # id: meta
-        # run: |
-          # for changed_file in ${{ steps.changed-files.outputs.all }}; do
-            # if [[ ${changed_file} =~ ^.*recipes\/.*meta\.(yml|yaml)$ ]];
-            # then
-              # echo "::set-output name=META_YAML::${changed_file}";
-              # exit 0
-            # fi
-          # done
-          # exit 1 # Fail - meta.yaml required
+      - name: Locate Pull Requests meta.yaml
+        id: meta
+        run: |
+          for changed_file in ${{ steps.changed-files.outputs.all }}; do
+            if [[ ${changed_file} =~ ^.*recipes\/.*meta\.(yml|yaml)$ ]];
+            then
+              echo "::set-output name=META_YAML::${changed_file}";
+              exit 0
+            fi
+          done
+          exit 1 # Fail - meta.yaml required
